
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 04 16:33:03 CET 2003
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 21;
  public static final int TESIS = 17;
  public static final int ENDIF = 6;
  public static final int THEN = 5;
  public static final int IN = 9;
  public static final int CIERRALLAVE = 14;
  public static final int PAREN = 16;
  public static final int LOCAL = 11;
  public static final int IF = 4;
  public static final int CLOG = 19;
  public static final int IGUALQUE = 7;
  public static final int TIPO = 20;
  public static final int COMA = 15;
  public static final int EOF = 0;
  public static final int PROG = 8;
  public static final int ABRELLAVE = 13;
  public static final int error = 1;
  public static final int ASOP = 3;
  public static final int PUNTOCOMA = 2;
  public static final int OUT = 10;
  public static final int CENT = 18;
  public static final int MAS = 12;
}

